version: '3.8'
services:
  api:
    build: ./api
    container_name: backend
    env_file: .env
    ports:
      - '5555:5555'
    volumes:
      - ./api:/app
      - ./app/node_modules
  client:
    build: ./client
    container_name: frontend
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
